apiVersion: apps/v1
kind: Deployment
metadata:
  name: todolist
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todolist
  template:
    metadata:
      labels:
        app: todolist
    spec:
      containers:
        - name: todolist
          image: 872583825157.dkr.ecr.ap-southeast-1.amazonaws.com/periodictable/atm
          ports:
            - containerPort: 8080
          env:
            - name: PROFILES_ACTIVE
              value: "dev"
      # imagePullSecrets:
      #   - name: ecr-registry-secret