apiVersion: apps/v1
kind: Deployment
metadata:
  name: todolist
  namespace: todolist
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todolist
  template:
    metadata:
      labels:
        app: todolist
    spec:
      containers:
        - name: todolist
          image: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY_NAME }}
          ports:
            - containerPort: 8080
          env:
            - name: PROFILES_ACTIVE
              value: "dev"
      imagePullSecrets:
        - name: ecr-registry-secret