apiVersion: apps/v1
kind: Deployment
metadata:
  name: todolist
  namespace: todolist
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todolist
  template:
    metadata:
      labels:
        app: todolist
    spec:
      containers:
        - name: todolist
          image: 442387259505.dkr.ecr.ap-southeast-1.amazonaws.com/learn/todolist
          ports:
            - containerPort: 8080
          env:
            - name: PROFILES_ACTIVE
              value: "dev"
      imagePullSecrets:
        - name: ecr-registry-secret